name: Download GodotSteam Multiplayer Peer
description: Download and extract the GodotSteam Multiplayer Peer source code for use in compiling
inputs:
  ref:
    description: Branch to pull from
    default: "multiplayer-peer"
runs:
  using: "composite"
  steps:
    - name: Download and extract GodotSteam Multiplayer Peer
      uses: actions/checkout@v4
      with:
        repository: "grossqx/GodotSteam"
        path: "godotsteam_multiplayer"
        ref: ${{ inputs.ref }}

    - name: Copy GodotSteam
      shell: bash
      run: |
        cp -r godotsteam_multiplayer ./modules/godotsteam_multiplayer