name: Commit debug
run-name: Commit debug ${{ github.event.ref }}


on:
  workflow_dispatch:
    inputs:
      build_name:
        description: Will be displayed in console when launching builds and in the editor, next to the version.
        required: false
        type: string
        default: satellite_build
      # Used to pick the branch and version of SDK
      steamworks_sdk_tag:
        description: 'Steamworks SDK Github branch:'
        required: true
        type: string
        default: '1.59'
      # Used for file names
      godot_tag:
        description: 'Used for file names - Godot Github tag:'
        required: true
        type: string
        default: '4.2.1-stable'
      # Used for file names
      godotsteam_version:
        description: 'Used for file names - GodotSteam version number:'
        required: true
        type: string
        default: '4.6.1'


jobs:
  env-setup:
    uses: ./.github/workflows/setup-env.yml
    with:
      godot_tag: ${{ inputs.godot_tag }}
      godotsteam_version: ${{ inputs.godotsteam_version }}
      steamworks_sdk_tag: ${{ inputs.steamworks_sdk_tag }}

  # Linux

  create_dummy:
    needs: [env-setup]
    uses: ./.github/workflows/create_dummy.yml
    with:
      build_name: ${{ inputs.build_name }}
      godot_tag: ${{ inputs.godot_tag }}
      godot_version: ${{ needs.env-setup.outputs.godot_version }}
      steamworks_sdk_tag: ${{ inputs.steamworks_sdk_tag }}
    secrets:
      steamworks_sdk_repo: ${{ secrets.STEAMWORKS_REPO }}
      steamorks_ssh_deploy_key: ${{ secrets.STEAMWORKS_DEPLOY_KEY }}
      godot_encryption_key: ${{ secrets.GODOT_ENCRYPTION_KEY }}

  # Bundle everything

  commit-binaries-to-repo:
    #needs: [env-setup, build-linux, build-windows]
    needs: [env-setup, build-linux]
    uses: ./.github/workflows/commit-binaries-to-repo.yml
    with:
      zip_tag: ${{ needs.env-setup.outputs.zip_tag }}
    secrets:
      #destination-github-username: ${{ secrets.GODOT_BIN_REPO_OWNER }}
      destination-github-username: grossqx
      #destination-repository-name: ${{ secrets.GODOT_BIN_REPO_NAME}}
      destination-repository-name: godot-bin
      repo-deploy-key: ${{ secrets.GODOT_BIN_DEPLOY_KEY }}