name: Context testing
run-name: Context testing 🚀
on:
  workflow_dispatch:
    inputs:
      godot_encryption_key:
        description: Compile key testing
        default: ''
jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Checking encryption option
        shell: bash
        run: |
          if [[ "${{ inputs.godot_encryption_key }}" != '' ]]; then
            echo "Building encrypted binary with key: ${{ inputs.godot_encryption_key }}"
            export SCRIPT_AES256_ENCRYPTION_KEY="${{ inputs.godot_encryption_key }}"
          else
            echo "Building binary without encryption"
            unset SCRIPT_AES256_ENCRYPTION_KEY
          fi
      
      - name: Checking encryption option
        shell: bash
        run: |
          if [[ ${{ inputs.godot_encryption_key != '' }} ]]; then
            echo "Building encrypted binary ${{ inputs.godot_encryption_key}}"
            export SCRIPT_AES256_ENCRYPTION_KEY="${{ inputs.godot_encryption_key}}"
          else
            echo "Building binary without encryption "${{ inputs.godot_encryption_key}}"
            unset SCRIPT_AES256_ENCRYPTION_KEY
          fi